### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by mzamoun** [multimediabs/cudl#16]
I have the following file tree:
root.vxml
scripts/config.js
app/index.vxml
<p>
where index.vxml contains in his head : 
<code>
< vxml version="2.1" xmlns="http://www.w3.org/2001/vxml" application="../root.vxml" xml:lang="fr-FR" >
</code>
<p>
and root.vxml contains : 
<script src="./scripts/config.js" />
<p>
The Interpreter start with  : app/index.vxml 
<p>
Then I have this error : 
<pre>
java.io.FileNotFoundException: ...\scripts\config.js (Le chemin d’accès spécifié est introuvable)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.(Unknown Source)
at java.io.FileInputStream.(Unknown Source)
at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
at java.net.URL.openStream(Unknown Source)
at cudl.script.InterpreterVariableDeclaration.evaluateFileScript(InterpreterVariableDeclaration.java:102)
at cudl.InterpreterContext.declareVariable(InterpreterContext.java:220)
at cudl.InterpreterContext.declareRootScopeVariableIfNeeded(InterpreterContext.java:166)
at cudl.InterpreterContext.buildDocument(InterpreterContext.java:130)
at cudl.InterpreterContext.(InterpreterContext.java:73)
at cudl.Interpreter.(Interpreter.java:34)
at cudl.Interpreter.(Interpreter.java:30)
...
</pre>

**Comment by mzamoun** [comment]
details of the file tree:
root.vxml
scripts/config.js
app/index.vxml

**Comment by mzamoun** [comment]
formatting error lines : 
java.io.FileNotFoundException: ...\scripts\config.js (Le chemin d’accès spécifié est introuvable)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at cudl.script.InterpreterVariableDeclaration.evaluateFileScript(InterpreterVariableDeclaration.java:102)
	at cudl.InterpreterContext.declareVariable(InterpreterContext.java:220)
	at cudl.InterpreterContext.declareRootScopeVariableIfNeeded(InterpreterContext.java:166)
	at cudl.InterpreterContext.buildDocument(InterpreterContext.java:130)
	at cudl.InterpreterContext.<init>(InterpreterContext.java:73)
	at cudl.Interpreter.<init>(Interpreter.java:34)
	at cudl.Interpreter.<init>(Interpreter.java:30)

**Comment by sdiawara** [comment]
The commit https://github.com/multimediabs/cudl/commit/9f20c5ae6d3143285c6438b741e69a048902e55a 

Could you confirm please ?

**Comment by mzamoun** [comment]
How to get this commit with line command and/or under eclipse ?

**Comment by mzamoun** [comment]
Yes it does the job 👍

**Comment by sdiawara** [comment]
Ok good
