### ISSUE TITLE
EcmaError: ReferenceError

### ISSUE THREAD

**Issue by mzamoun** [multimediabs/cudl#17]
org.mozilla.javascript.EcmaError: ReferenceError: "Version_APP" n'est pas défini (eval code#1(eval)#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3848)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1781)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1780)
	at script(eval code#1(eval):1)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:854)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
	at org.mozilla.javascript.ScriptRuntime.evalSpecial(ScriptRuntime.java:2599)
	at org.mozilla.javascript.NativeGlobal.js_eval(NativeGlobal.java:530)
	at org.mozilla.javascript.NativeGlobal.execIdCall(NativeGlobal.java:191)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
	at org.mozilla.javascript.ScriptRuntime.callSpecial(ScriptRuntime.java:2463)
	at org.mozilla.javascript.optimizer.OptRuntime.callSpecial(OptRuntime.java:165)

I have the following file tree:
root.vxml
scripts/config.js
app/index.vxml

 where index.vxml contains in his head : < vxml version="2.1" xmlns="http://www.w3.org/2001/vxml" application="../root.vxml" xml:lang="fr-FR" >

and root.vxml contains : <script src="./scripts/config.js" />

and scripts/config.js contains : 
var Version_APP	= "V1.0/";

The Interpreter start with : app/index.vxml

**Comment by sdiawara** [comment]
See there an example with the same tree : 

https://github.com/multimediabs/cudl/tree/master/src/test/resources/issues/16

**Comment by mzamoun** [comment]
Is there a solution for this problem ?

**Comment by mzamoun** [comment]
Is there a solution for this problem ?

**Comment by mzamoun** [comment]
one solution is to set in test.js :
Version_APP = "1.0";

Then it works.

But why ?

**Comment by sdiawara** [comment]
This is due to the fact that the eval expression is not executed in the correct scope

**Comment by mzamoun** [comment]
thanks
