### ISSUE TITLE
NullPointer when interpreting subdialog

### ISSUE THREAD

**Issue by mzamoun** [multimediabs/cudl#20]
java.lang.NullPointerException
	at cudl.InterpreterEventHandler.searchEventHandlers(InterpreterEventHandler.java:155)
	at cudl.InterpreterEventHandler.searchEventHandlerForSelectedFormItem(InterpreterEventHandler.java:128)
	at cudl.InterpreterEventHandler.doEvent(InterpreterEventHandler.java:54)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:91)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:177)
	at cudl.SubdialogTag.interpret(VoiceXmlNode.java:1055)
	at cudl.FormTag.interpret(VoiceXmlNode.java:185)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:85)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:168)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:168)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:168)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:168)
	at cudl.InternalInterpreter.interpret(InternalInterpreter.java:168)
	at cudl.Interpreter.start(Interpreter.java:45)
...

**Comment by mzamoun** [comment]
it was just an error in my vxml file.
